version: '3'

services:
  go-wallet-core:
    build:
      context: ./ms-wallet-core
    platform: linux/amd64
    tty: true
    restart: always
    depends_on:
      wallet-core-mysql:
        condition: service_healthy
    volumes:
      - ./ms-wallet-core:/app
    networks:
      - wallet
    ports:
      - 8080:8080

  go-wallet-balance:
    build:
      context: ./ms-wallet-balance
    platform: linux/amd64
    tty: true
    restart: always
    depends_on:
      wallet-balance-mysql:
        condition: service_healthy
    volumes:
      - ./ms-wallet-balance:/app
    networks:
      - wallet
    ports:
      - 3003:3003

  wallet-core-mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    container_name: wallet-core-mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      start_period: 2s
      interval: 3s
      timeout: 5s
      retries: 30
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: 3307
      MYSQL_ROOT_HOST: '%'
    networks:
      - wallet
    ports:
      - 3307:3307
    volumes:
      - core-mysql-data:/var/lib/mysql

  wallet-balance-mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    container_name: wallet-balance-mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      start_period: 2s
      interval: 3s
      timeout: 5s
      retries: 30
    tty: true
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: 3308
      MYSQL_ROOT_HOST: '%'
    networks:
      - wallet
    ports:
      - 3308:3308
    volumes:
      - balance-mysql-data:/var/lib/mysql

  zookeeper:
    image: "confluentinc/cp-zookeeper:6.1.0"
    platform: linux/amd64
    container_name: zookeeper
    networks:
      - wallet
    ports:
      - 2181:2181
    environment:
      TZ: Sao_Paulo/Brazil
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: "confluentinc/cp-enterprise-kafka:6.1.0"
    platform: linux/amd64
    container_name: kafka
    depends_on:
      - zookeeper
    networks:
      - wallet
    ports:
      # Exposes 9092 for external connections to the broker
      # Use kafka:29092 for connections internal on the docker network
      # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
      - '9092:9092'
    environment:
      TZ: Sao_Paulo/Brazil
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      CONFLUENT_METRICS_ENABLE: 'false'

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.3.0
    platform: linux/amd64
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka
    networks:
      - wallet
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:29092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

networks:
  wallet:
    driver: bridge

volumes:
  core-mysql-data:
    name: wallet_core-mysql-data
  balance-mysql-data:
    name: wallet_balance-mysql-data
    
